In [4]:
import numpy as np
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
v= np.array([1,2,3,4])
print(v)
print(v.shape)
print(v[0])

v = np.arange(1,5).reshape(1,4)
print(v)
print(v.shape)
v.shape
print(v[0])

[1 2 3 4]
(4,)
1
[[1 2 3 4]]
(1, 4)
[1 2 3 4]
