# Admission Numbers

- CSS/00099/022
- CSS/00072/021

In [7]:
import numpy as np
vector = [i for i in range(50)]
matrix = np.array(vector).reshape(10,5)
column_averages = np.mean(matrix, axis=0)
row_averages = np.mean(matrix, axis=1)
print(vector)
print(matrix)
print("Column averages:", column_averages)
print("Row averages:", row_averages)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
Column averages: [22.5 23.5 24.5 25.5 26.5]
Row averages: [ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47.]


In [14]:
matrix = np.array(vector).reshape(10,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [10]:
column_averages = np.mean(matrix, axis=0)
print("Column averages:", column_averages)


Column averages: [22.5 23.5 24.5 25.5 26.5]


In [12]:
row_averages = np.mean(matrix, axis=1)
print("Row averages:", row_averages)

Row averages: [ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47.]


In [4]:
import numpy as np

# Create a 10x5 matrix with random values for demonstration
np.random.seed(0)  # Seed for reproducibility
matrix = np.random.randint(1, 100, size=(10, 5))

print("Original Matrix:")
print(matrix)

# Function to find the 4 highest values in the row, 2 from each side of the first column
def replace_first_column(matrix):
    for i in range(matrix.shape[0]):  # Iterate through each row
        row = matrix[i, :]
        
        # Get values left and right of the first column
        left_side = row[1:3]  # Values in the second and third column
        right_side = row[3:5]  # Values in the fourth and fifth column

        # Get the 4 highest values from left and right
        highest_values = np.sort(np.concatenate((left_side, right_side)))[-4:]

        # Replace the value in the first column with the sum of these highest values
        matrix[i, 0] = np.sum(highest_values)
        
    return matrix

# Apply the function to the matrix
modified_matrix = replace_first_column(matrix)

print("\nModified Matrix (First column replaced):")
print(modified_matrix)



Original Matrix:
[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]
 [48 65 83 89 50]
 [30 20 20 15 40]
 [33 66 10 58 33]
 [32 75 24 36 76]]

Modified Matrix (First column replaced):
[[249  48  65  68  68]
 [231  84  22  37  88]
 [250  89  89  13  59]
 [264  40  88  47  89]
 [215  38  26  78  73]
 [252  21  81  70  80]
 [287  65  83  89  50]
 [ 95  20  20  15  40]
 [167  66  10  58  33]
 [211  75  24  36  76]]


In [5]:
import numpy as np
np.mean?

